### ISSUE TITLE
Issue #1: Implement a power-law random number generator

### ISSUE THREAD

**Issue by charlesfrye** [dcjohnston/deadleaves#1]
yo @dcjohnston:

The scales of the emojis will be drawn from a power-law distribution. Because JS, AFAIK, does not provide support for sampling from this distribution :cry:, we need to implement it ourselves.

We can do this using the inverse of the cumulative density function (CDF) to map from probabilities to values. The cumulative density function at x records the probability that a random variable will take on a value less than or equal to x. For well-behaved distributions, this function is monotone increasing and bounded by 0 and 1, so it produces an invertible mapping between the set of possible values and the unit interval [0,1]. 

Therefore, we simply need to generate random values between 0 and 1 using Math.Random, then map them using the inverse CDF to generate our scales. :+1: 

The following python code defines a (higher-order) function that returns inverse CDFs for power-laws with different exponents `alpha`. Roughly speaking, a higher power means that smaller values are produced. We also need to define a minimum value for the scale, here `xmin`, so that we don't find ourselves in the awkward position of rendering emoji of zero size! :no_good:

```
def getInversePowerCDF(alpha,xmin):
    def inversePowerCDF(p):
        return alpha*xmin*p**(-1/(alpha+1))
    return inversePowerCDF
```

Once we've defined the function `inversePowerCDF` based on a user-provided `alpha`, we need to produce a list of scales:

```
scales = [] #initialize
for eachEmoji in range(numEmojis):
    p = Math.Random()
    scales.append(inversePowerCDF(p))
```

This might also be a convenient time to produce a list of x and y locations - tuples in [0,1] x [0,1] - using Math.Random as well. If there's an efficient vectorization procedure for RNGs in JS, we can cheaply produce the 3 by numEmojis array of random numbers all at once! :100: :ok_hand: :+1: mmhmm

**Comment by charlesfrye** [comment]
Clarification: `alpha` here is a `Float`, usually between 1 and 2, and so the `**` operation is exponentiation to a (fractional) floating point power. I'm not sure if this is implemented in JS. If it is not, we'll need to implement that ourselves as well. Not too difficult, especially since we don't need hella precision.

**Comment by dcjohnston** [comment]
Forutnately javascript has neither floats nor integers, only Numbers. Math.pow === **. Pushing shortly
